name: CI

on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Unit Test
        run:  make test
      - name: Template Unit Tests
        run:  make test-templates
      - name: Lint
        run: make check
      - name: Check that 'func.yaml schema' is up-to-date
        run: make schema-check

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: "1.16"
      # Standard build tasks
      - name: Build
        run: make cross-platform
      # Upload all build artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: OSX Binary
          path: func_darwin_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: Linux Binary
          path: func_linux_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Binary
          path: func_windows_amd64.exe
  publish-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: "1.16"
      - uses: imjason/setup-ko
        run: ko publish -B ./cmd/func